name: 'build'
on:
  push:

jobs:
  build-examples:
    runs-on: [self-hosted, linux, x64]

    steps:

      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Build
        run: make all-build
