name: 'build'
on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: [self-hosted, linux, x64]

    permissions:
      contents: read
      packages: write

    steps:

      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Build and Package
        run: echo "TODO"
